### PR TITLE
Feature/add check for only one returned attribute per peer

### PR DESCRIPTION
**Pull request by Milena-Czierlinski**

### CODE REVIEW

**Comment by stnmtz** [comment]
I would say we should consume the database as the single source of truth with no errors/inconsistency in mind. Starting to implement consistency checks (for states which should actually never happen) within certain functions/use-cases feels weird in my opinion. In addition, validating those things within the functions and throwing errors would require testing the functions for unreal no-no-never-cases to throw those errors. And we would have quite some consistency checks to implement within all the current functionality. On the other hand, a warning could be provided in the log statements, that such an inconsistency occured (but hey, who reads the logs?).

And don't get me wrong here: Of course we need consistency checks before/when/after we change something in the database. But we should not check consistency while just reading from the database.

Nevertheless, it might make sense to have dedicated consistency checks for such things. And I second Milena in doing our best to have a good input validation which blocks anybody from doing stupid things.

@tnotheis @jkoenig134 Please provide your feedback.

**Comment by jkoenig134** [comment]
@stnmtz I agree with you

**Comment by tnotheis** [comment]
@stnmtz I agree as well.

**Comment by Milena-Czierlinski** [comment]
So do you prefer to log a warning or just omit it altogether?

**Comment by tnotheis** [comment]
I would omit it. If we start logging warnings for all kinds of validation issues, the get methods would be too messy.

**Comment by stnmtz** [comment]
I would vote for not implementing the check

**Pull request closed without merging**
